### ISSUE TITLE
[Feature request] Add support for organisation token as well

### ISSUE THREAD

**Issue by smorimoto** [axiomhq/axiom-syslog-proxy#29]
```json
{
  "level": "info",
  "ts": 1691260032.7793918,
  "logger": "axiom-syslog-proxy",
  "caller": "cmd/cmd.go:71",
  "msg": "starting",
  "release": "0.4.1",
  "revision": "92d4c9b",
  "build_date": "2021-11-08T10:14:39Z",
  "build_user": "goreleaser",
  "go_version": "go1.17.2"
}
```

```json
{
  "level": "error",
  "ts": 1691260032.7797287,
  "logger": "axiom-syslog-proxy",
  "caller": "cmd/cmd.go:94",
  "msg": "create axiom client",
  "error": "invalid access token"
}
```

```json
{
  "level": "warn",
  "ts": 1691260032.7798183,
  "logger": "axiom-syslog-proxy",
  "caller": "cmd/cmd.go:60",
  "msg": "stopped"
}
```

**Comment by lukasmalkmus** [comment]
Thanks for the report. I'll release an updated version later today 👍

**Comment by smorimoto** [comment]
@lukasmalkmus Thank you! This really helped our team to send network router syslogs to Axiom!

**Comment by lukasmalkmus** [comment]
@smorimoto I just cut `v0.5.0`. Images and binaries should be ready to go any minute. I'll take a look at `distroless` and do some local testing, as well. Will cut another release after that (most likely `v0.6.0`). Go 1.21 also made its debut. Since this repo doesn't get updated to often, lemme check if we should build with the latest Go release and if so, expect `v0.7.0` by the end of the week.

**Comment by smorimoto** [comment]
@lukasmalkmus 0.5 works well for me with an org token! I also built the Distroless image locally, and it worked well for me, at least.

**Comment by smorimoto** [comment]
I don't have a strong opinion on whether to build with the latest Go release. As long as it runs on Distroless with a statically linked binary, I wouldn't think it would be a problem even if left untouched for several years 🙂
